[0m13:38:10.814689 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f68bd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d0af90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111ce5950>]}


============================== 13:38:10.822537 | e2896dc7-6391-4cb1-a456-f9752ea7180a ==============================
[0m13:38:10.822537 [info ] [MainThread]: Running with dbt=1.6.3
[0m13:38:10.823582 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/rtewelde/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:38:10.824687 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/rtewelde/dbt_demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:38:10.825787 [debug] [MainThread]: Command `dbt run` failed at 13:38:10.825540 after 0.05 seconds
[0m13:38:10.826287 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111fd51d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111fc7810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1119d65d0>]}
[0m13:38:10.826804 [debug] [MainThread]: Flushing usage events
